language: node_js
node_js:
  - '10'
script:
  - npm install
  - npm run lint
  - npm test
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main
