language: node_js
node_js:
  - '10'
script:
  - npm install
  - npm run build
  - npm start
cache:
  directories:
    - node_modules
notifications:
  email:
    on_success: never
    on_failure: never
deploy:
  provider: pages
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  on:
    branch: main
